/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AskRegsRouteImport } from './routes/ask-regs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEdSourceDeskLookupRouteImport } from './routes/api/ed-source-desk/lookup'
import { Route as ApiEdSourceDeskGoldensRouteImport } from './routes/api/ed-source-desk/goldens'
import { Route as ApiEdSourceDeskAdminImportRouteImport } from './routes/api/ed-source-desk/admin/import'
import { Route as ApiEdSourceDeskExplainRouteImport } from './routes/api/ed-source-desk/explain'

const AskRegsRoute = AskRegsRouteImport.update({
  id: '/ask-regs',
  path: '/ask-regs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdSourceDeskLookupRoute = ApiEdSourceDeskLookupRouteImport.update({
  id: '/api/ed-source-desk/lookup',
  path: '/api/ed-source-desk/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdSourceDeskGoldensRoute = ApiEdSourceDeskGoldensRouteImport.update({
  id: '/api/ed-source-desk/goldens',
  path: '/api/ed-source-desk/goldens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdSourceDeskAdminImportRoute =
  ApiEdSourceDeskAdminImportRouteImport.update({
    id: '/api/ed-source-desk/admin/import',
    path: '/api/ed-source-desk/admin/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEdSourceDeskExplainRoute = ApiEdSourceDeskExplainRouteImport.update({
  id: '/api/ed-source-desk/explain',
  path: '/api/ed-source-desk/explain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-regs': typeof AskRegsRoute
  '/api/ed-source-desk/goldens': typeof ApiEdSourceDeskGoldensRoute
  '/api/ed-source-desk/lookup': typeof ApiEdSourceDeskLookupRoute
  '/api/ed-source-desk/admin/import': typeof ApiEdSourceDeskAdminImportRoute
  '/api/ed-source-desk/explain': typeof ApiEdSourceDeskExplainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-regs': typeof AskRegsRoute
  '/api/ed-source-desk/goldens': typeof ApiEdSourceDeskGoldensRoute
  '/api/ed-source-desk/lookup': typeof ApiEdSourceDeskLookupRoute
  '/api/ed-source-desk/admin/import': typeof ApiEdSourceDeskAdminImportRoute
  '/api/ed-source-desk/explain': typeof ApiEdSourceDeskExplainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask-regs': typeof AskRegsRoute
  '/api/ed-source-desk/goldens': typeof ApiEdSourceDeskGoldensRoute
  '/api/ed-source-desk/lookup': typeof ApiEdSourceDeskLookupRoute
  '/api/ed-source-desk/admin/import': typeof ApiEdSourceDeskAdminImportRoute
  '/api/ed-source-desk/explain': typeof ApiEdSourceDeskExplainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask-regs'
    | '/api/ed-source-desk/goldens'
    | '/api/ed-source-desk/lookup'
    | '/api/ed-source-desk/admin/import'
    | '/api/ed-source-desk/explain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask-regs'
    | '/api/ed-source-desk/goldens'
    | '/api/ed-source-desk/lookup'
    | '/api/ed-source-desk/admin/import'
    | '/api/ed-source-desk/explain'
  id:
    | '__root__'
    | '/'
    | '/ask-regs'
    | '/api/ed-source-desk/goldens'
    | '/api/ed-source-desk/lookup'
    | '/api/ed-source-desk/admin/import'
    | '/api/ed-source-desk/explain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRegsRoute: typeof AskRegsRoute
  ApiEdSourceDeskGoldensRoute: typeof ApiEdSourceDeskGoldensRoute
  ApiEdSourceDeskLookupRoute: typeof ApiEdSourceDeskLookupRoute
  ApiEdSourceDeskAdminImportRoute: typeof ApiEdSourceDeskAdminImportRoute
  ApiEdSourceDeskExplainRoute: typeof ApiEdSourceDeskExplainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ask-regs': {
      id: '/ask-regs'
      path: '/ask-regs'
      fullPath: '/ask-regs'
      preLoaderRoute: typeof AskRegsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ed-source-desk/lookup': {
      id: '/api/ed-source-desk/lookup'
      path: '/api/ed-source-desk/lookup'
      fullPath: '/api/ed-source-desk/lookup'
      preLoaderRoute: typeof ApiEdSourceDeskLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ed-source-desk/goldens': {
      id: '/api/ed-source-desk/goldens'
      path: '/api/ed-source-desk/goldens'
      fullPath: '/api/ed-source-desk/goldens'
      preLoaderRoute: typeof ApiEdSourceDeskGoldensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ed-source-desk/admin/import': {
      id: '/api/ed-source-desk/admin/import'
      path: '/api/ed-source-desk/admin/import'
      fullPath: '/api/ed-source-desk/admin/import'
      preLoaderRoute: typeof ApiEdSourceDeskAdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ed-source-desk/explain': {
      id: '/api/ed-source-desk/explain'
      path: '/api/ed-source-desk/explain'
      fullPath: '/api/ed-source-desk/explain'
      preLoaderRoute: typeof ApiEdSourceDeskExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRegsRoute: AskRegsRoute,
  ApiEdSourceDeskGoldensRoute: ApiEdSourceDeskGoldensRoute,
  ApiEdSourceDeskLookupRoute: ApiEdSourceDeskLookupRoute,
  ApiEdSourceDeskAdminImportRoute: ApiEdSourceDeskAdminImportRoute,
  ApiEdSourceDeskExplainRoute: ApiEdSourceDeskExplainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
