/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEdSourceDeskLookupRouteImport } from './routes/api/ed-source-desk/lookup'
import { Route as ApiEdSourceDeskGoldensRouteImport } from './routes/api/ed-source-desk/goldens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdSourceDeskLookupRoute = ApiEdSourceDeskLookupRouteImport.update({
  id: '/api/ed-source-desk/lookup',
  path: '/api/ed-source-desk/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdSourceDeskGoldensRoute = ApiEdSourceDeskGoldensRouteImport.update({
  id: '/api/ed-source-desk/goldens',
  path: '/api/ed-source-desk/goldens',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ed-source-desk/goldens': typeof ApiEdSourceDeskGoldensRoute
  '/api/ed-source-desk/lookup': typeof ApiEdSourceDeskLookupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ed-source-desk/goldens': typeof ApiEdSourceDeskGoldensRoute
  '/api/ed-source-desk/lookup': typeof ApiEdSourceDeskLookupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ed-source-desk/goldens': typeof ApiEdSourceDeskGoldensRoute
  '/api/ed-source-desk/lookup': typeof ApiEdSourceDeskLookupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ed-source-desk/goldens' | '/api/ed-source-desk/lookup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ed-source-desk/goldens' | '/api/ed-source-desk/lookup'
  id:
    | '__root__'
    | '/'
    | '/api/ed-source-desk/goldens'
    | '/api/ed-source-desk/lookup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEdSourceDeskGoldensRoute: typeof ApiEdSourceDeskGoldensRoute
  ApiEdSourceDeskLookupRoute: typeof ApiEdSourceDeskLookupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ed-source-desk/lookup': {
      id: '/api/ed-source-desk/lookup'
      path: '/api/ed-source-desk/lookup'
      fullPath: '/api/ed-source-desk/lookup'
      preLoaderRoute: typeof ApiEdSourceDeskLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ed-source-desk/goldens': {
      id: '/api/ed-source-desk/goldens'
      path: '/api/ed-source-desk/goldens'
      fullPath: '/api/ed-source-desk/goldens'
      preLoaderRoute: typeof ApiEdSourceDeskGoldensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEdSourceDeskGoldensRoute: ApiEdSourceDeskGoldensRoute,
  ApiEdSourceDeskLookupRoute: ApiEdSourceDeskLookupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
